import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/proj/nav";
import { Toaster } from "react-hot-toast";
import { AdminProvider } from "@/context/admincontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AdminProvider>
          <div className="relative min-h-screen w-full overflow-y-scroll overflow-x-hidden no-scrollbar">
            <Nav />
            {children}
            <Toaster position="top-center" reverseOrder={false} />
          </div>
        </AdminProvider>
      </body>
    </html>
  );
}
